version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: saas_entreprise
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_entreprise
    ports: 
      - "5439:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db: