version: '3.8'
services:
  app:
    build:
      context: .
    image: nextjs-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL="postgresql://website_builder_saas:postgres@db:5432/website_builder_saas"
    depends_on:
      - db
    restart: unless-stopped
   
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: website_builder_saas
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: website_builder_saas
    ports: 
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db: